incomplete. was just using this to understand how ppo works
https://github.com/nikhilbarhate99/PPO-PyTorch/blob/master/PPO.py

In [1]:
import torch
import torch.nn as nn
from torch.distributions import Categorical
import gym

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [5]:
class Memory:
    def __init__(self):
        self.actions = []
        self.states = []
        self.logprobs = []
        self.rewards = []
        self.is_terminals = []
    
    def clear_memory(self):
        del self.actions[:]
        del self.states[:]
        del self.logprobs[:]
        del self.rewards[:]
        del self.is_terminals[:]


In [13]:
class ActorCritic(nn.Module):
    def __init__(self, state_dim, action_dim, n_latent_var):
        super(ActorCritic, self).__init__()
        self.affine = nn.Linear(state_dim, n_latent_var)
        
        # actor
        self.action_layer = nn.Sequential(
                nn.Linear(state_dim, n_latent_var),
                nn.Tanh(),
                nn.Linear(n_latent_var, n_latent_var),
                nn.Tanh(),
                nn.Linear(n_latent_var, action_dim),
                nn.Softmax(dim=-1)
                )
        
        # critic
        self.value_layer = nn.Sequential(
                nn.Linear(state_dim, n_latent_var),
                nn.Tanh(),
                nn.Linear(n_latent_var, n_latent_var),
                nn.Tanh(),
                nn.Linear(n_latent_var, 1)
                )
        
    def forward(self):
        raise NotImplementedError
        
    def act(self, state, memory):
        state = torch.from_numpy(state).float().to(device) 
        action_probs = self.action_layer(state)
        dist = Categorical(action_probs)
        action = dist.sample()
        
        memory.states.append(state)
        memory.actions.append(action)
        memory.logprobs.append(dist.log_prob(action))
        
        return action.item()
    
    def evaluate(self, state, action):
        action_probs = self.action_layer(state)
        dist = Categorical(action_probs)
        
        action_logprobs = dist.log_prob(action)
        dist_entropy = dist.entropy()
        
        state_value = self.value_layer(state)
        
        return action_logprobs, torch.squeeze(state_value), dist_entropy

In [19]:
rewards = []
discounted_reward = 0
for reward, is_terminal in zip(reversed(memory.rewards), reversed(memory.is_terminals)):
    if is_terminal:
        discounted_reward = 0
    discounted_reward = reward + (gamma * discounted_reward)
    rewards.insert(0, discounted_reward)

# Normalizing the rewards:
rewards = torch.tensor(rewards).to(device)
rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-5)
print(rewards)

tensor([ 1.2497,  0.6415, -0.5182, -0.0479, -1.3251], device='cuda:0')


In [23]:
# convert list to tensor
old_states = torch.stack(memory.states).to(device).detach()
old_actions = torch.stack(memory.actions).to(device).detach()
old_logprobs = torch.stack(memory.logprobs).to(device).detach()

In [34]:
# evaluate
action_probs = ppo.policy.action_layer(old_states)
dist = Categorical(action_probs)

action_logprobs = dist.log_prob(old_actions)
dist_entropy = dist.entropy()

# state_value = self.value_layer(state)

# return action_logprobs, torch.squeeze(state_value), dist_entropy

In [41]:
old_logprobs

tensor([-1.4450, -1.6404, -1.2669, -1.6361, -1.2707], device='cuda:0')

In [42]:
action_logprobs

tensor([-1.4450, -1.6404, -1.2669, -1.6361, -1.2707], device='cuda:0',
       grad_fn=<SqueezeBackward1>)

In [40]:
action_probs

tensor([[0.2357, 0.1935, 0.2835, 0.2873],
        [0.2358, 0.1939, 0.2829, 0.2874],
        [0.2352, 0.1949, 0.2817, 0.2882],
        [0.2352, 0.1947, 0.2818, 0.2883],
        [0.2345, 0.1958, 0.2806, 0.2890]], device='cuda:0',
       grad_fn=<SoftmaxBackward>)

In [44]:
ppo.action_layer([ 0.0022,  1.4151,  0.2234,  0.1852, -0.0025, -0.0506,  0.0000,  0.0000])

AttributeError: 'PPO' object has no attribute 'action_layer'

In [35]:
action_logprobs

tensor([-1.4450, -1.6404, -1.2669, -1.6361, -1.2707], device='cuda:0',
       grad_fn=<SqueezeBackward1>)

In [37]:
action_probs

tensor([[0.2357, 0.1935, 0.2835, 0.2873],
        [0.2358, 0.1939, 0.2829, 0.2874],
        [0.2352, 0.1949, 0.2817, 0.2882],
        [0.2352, 0.1947, 0.2818, 0.2883],
        [0.2345, 0.1958, 0.2806, 0.2890]], device='cuda:0',
       grad_fn=<SoftmaxBackward>)

In [36]:
dist_entropy

tensor([1.3742, 1.3743, 1.3746, 1.3745, 1.3747], device='cuda:0',
       grad_fn=<NegBackward>)

In [11]:
class PPO:
    def __init__(self, state_dim, action_dim, n_latent_var, lr, betas, gamma, K_epochs, eps_clip):
        self.lr = lr
        self.betas = betas
        self.gamma = gamma
        self.eps_clip = eps_clip
        self.K_epochs = K_epochs
        
        self.policy = ActorCritic(state_dim, action_dim, n_latent_var).to(device)
        self.optimizer = torch.optim.Adam(self.policy.parameters(), lr=lr, betas=betas)
        self.policy_old = ActorCritic(state_dim, action_dim, n_latent_var).to(device)
        self.policy_old.load_state_dict(self.policy.state_dict())
        
        self.MseLoss = nn.MSELoss()
    
    def update(self, memory):   
        # Monte Carlo estimate of state rewards:
        rewards = []
        discounted_reward = 0
        for reward, is_terminal in zip(reversed(memory.rewards), reversed(memory.is_terminals)):
            if is_terminal:
                discounted_reward = 0
            discounted_reward = reward + (self.gamma * discounted_reward)
            rewards.insert(0, discounted_reward)
        
        # Normalizing the rewards:
        rewards = torch.tensor(rewards).to(device)
        rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-5)
        
        # convert list to tensor
        old_states = torch.stack(memory.states).to(device).detach()
        old_actions = torch.stack(memory.actions).to(device).detach()
        old_logprobs = torch.stack(memory.logprobs).to(device).detach()
        
        # Optimize policy for K epochs:
        for _ in range(self.K_epochs):
            # Evaluating old actions and values :
            logprobs, state_values, dist_entropy = self.policy.evaluate(old_states, old_actions)
            
            # Finding the ratio (pi_theta / pi_theta__old):
            ratios = torch.exp(logprobs - old_logprobs.detach())
                
            # Finding Surrogate Loss:
            advantages = rewards - state_values.detach()
            surr1 = ratios * advantages
            surr2 = torch.clamp(ratios, 1-self.eps_clip, 1+self.eps_clip) * advantages
            loss = -torch.min(surr1, surr2) + 0.5*self.MseLoss(state_values, rewards) - 0.01*dist_entropy
            
            # take gradient step
            self.optimizer.zero_grad()
            loss.mean().backward()
            self.optimizer.step()
        
        # Copy new weights into old policy:
        self.policy_old.load_state_dict(self.policy.state_dict())

In [7]:
############## Hyperparameters ##############
env_name = "LunarLander-v2"
# creating environment
env = gym.make(env_name)
state_dim = env.observation_space.shape[0]
action_dim = 4
render = False
solved_reward = 230         # stop training if avg_reward > solved_reward
log_interval = 20           # print avg reward in the interval
max_episodes = 50000        # max training episodes
max_timesteps = 300         # max timesteps in one episode
n_latent_var = 64           # number of variables in hidden layer
update_timestep = 2000      # update policy every n timesteps
lr = 0.002
betas = (0.9, 0.999)
gamma = 0.99                # discount factor
K_epochs = 4                # update policy for K epochs
eps_clip = 0.2              # clip parameter for PPO
random_seed = None

if random_seed:
    torch.manual_seed(random_seed)
    env.seed(random_seed)


In [14]:
memory = Memory()
ppo = PPO(state_dim, action_dim, n_latent_var, lr, betas, gamma, K_epochs, eps_clip)
print(lr,betas)

# logging variables
running_reward = 0
avg_length = 0
timestep = 0

# training loop
for i_episode in range(1, max_episodes+1):
    state = env.reset()
    for t in range(5):
        timestep += 1

        # Running policy_old:
        action = ppo.policy_old.act(state, memory)
        state, reward, done, _ = env.step(action)

        # Saving reward and is_terminal:
        memory.rewards.append(reward)
        memory.is_terminals.append(done)

        # update if its time
        if timestep % 5 == 0:
            break
#             ppo.update(memory)
#             memory.clear_memory()
#             timestep = 0

        running_reward += reward
        if render:
            env.render()
        if done:
            break
    break # just one episode
    avg_length += t

#     # stop training if avg_reward > solved_reward
#     if running_reward > (log_interval*solved_reward):
#         print("########## Solved! ##########")
#         torch.save(ppo.policy.state_dict(), './PPO_{}.pth'.format(env_name))
#         break

#     # logging
#     if i_episode % log_interval == 0:
#         avg_length = int(avg_length/log_interval)
#         running_reward = int((running_reward/log_interval))

#         print('Episode {} \t avg length: {} \t reward: {}'.format(i_episode, avg_length, running_reward))
#         running_reward = 0
#         avg_length = 0

0.002 (0.9, 0.999)
